/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 bottled_car.glb --transform
Files: bottled_car.glb [70.05MB] > /Users/gk/WebstormProjects/hello-cube/src/assets/models/bottled_car-transformed.glb [3.38MB] (95%)
Author: Urizel (https://sketchfab.com/urizel)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/bottled-car-cd38a415db8a4607ab9dd3cc67d27462
Title: Bottled car
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import model from '../assets/models/bottled_car-transformed.glb'

export function BottleCar(props) {
  const { nodes, materials } = useGLTF(model)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.BOTTLE_OUTSIDE} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.LIGHT} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.BOTTOM} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.BOTTLE_WOOD} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.BOTTLE_INSIDE} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.BASEMETAL} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.NAMEPLATE} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.GLASS_N_CHROME} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.INTERIOR} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(model)
